-- Create leads table for customer inquiries
CREATE TABLE IF NOT EXISTS public.leads
(
    lead_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    lead_name character varying NOT NULL,
    lead_email character varying NOT NULL,
    lead_phone character varying,
    lead_message text,
    inv_id integer NOT NULL,
    account_id integer,
    lead_status character varying DEFAULT 'New'::character varying,
    lead_created_date timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT leads_pkey PRIMARY KEY (lead_id),
    CONSTRAINT fk_leads_inventory FOREIGN KEY (inv_id)
        REFERENCES public.inventory (inv_id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_leads_account FOREIGN KEY (account_id)
        REFERENCES public.account (account_id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE SET NULL
); 